[project]
name = "py-uv-boilerplate"
version = "0.1.0"
description = "A cookiecutter template for a Python project using uv."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "prek>=0.3.4",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov>=7.1.0",
    "ty>=0.0.19",
]

[tool.isort]
profile = "black"
src_paths = "tests"
line_length = 80
include_trailing_comma = true
multi_line_output = 3

[tool.coverage.run]
source = ["{{cookiecutter.project_slug}}"]

[tool.coverage.report]
show_missing = true
