---
name: test

on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4

            - name: Set up uv
              run: curl -LsSf https://astral.sh/uv/0.4.4/install.sh | sh

            # We test stuff inside the project dir not root dir
            - name: Change to project directory and install dependencies
              run: |
                  cd {{cookiecutter.project_slug}}
                  uv sync --all-extras --dev

            - name: Run Tests
              run: |
                  cd {{cookiecutter.project_slug}}
                  uv run pytest
