---
name: On PR

on:
    pull_request:
        branches: [main]
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review

jobs:
    prek:
        uses: ./.github/workflows/job-prek.yml

    test:
        uses: ./.github/workflows/job-test.yml
        permissions:
            contents: read
            id-token: write

    save-pr-number:
        runs-on: ubuntu-latest
        steps:
            - name: Save PR number
              run: echo "${{ github.event.pull_request.number }}" > pr_number.txt

            - name: Upload PR number
              uses: actions/upload-artifact@v4
              with:
                  name: pr-number
                  path: pr_number.txt
                  retention-days: 5
